name: CI Build and Publish Api

on:
  push:
    branches: ["main", "develop", "feature/**", "release/**", "hotfix/**"]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'production' || 'preview' }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4

      - name: Determine Version
        id: version_step
        run: |
          dotnet tool restore
          dotnet gitversion /output buildserver /updateprojectfiles

      - name: Build and test
        run: |
          dotnet build "halcyon.sln"
          dotnet test "halcyon.sln"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Lowercase the repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v5
        with:
          file: ./Halcyon.Api/Dockerfile
          tags: |
            ghcr.io/${{ env.REPO }}-api:${{ env.GitVersion_SemVer }}
            ghcr.io/${{ env.REPO }}-api:${{ env.GitVersion_SemVer }}-${{ env.GitVersion_ShortSha }}
            ghcr.io/${{ env.REPO }}-api:${{ env.GitVersion_PreReleaseLabel || 'latest' }}
          context: .
          push: true
          provenance: false

      - name: Trigger deployment
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            --data "{\"imageUrl\":\"ghcr.io/${{ env.REPO }}-api:${{ env.GitVersion_SemVer }}-${{ env.GitVersion_ShortSha }}\"}" \
            https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID_API }}/deploys
