name: CI Build and Publish

on:
  push:
    branches: ["main", "develop", "feature/**", "release/**", "hotfix/**"]
  workflow_dispatch:

jobs:
  build-api:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'production' || 'preview' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4

      - name: Determine Version
        id: version_step
        run: |
          dotnet tool restore
          dotnet gitversion /output buildserver /updateprojectfiles

      - name: Build and test
        run: |
          dotnet build "halcyon.sln"
          dotnet test "halcyon.sln"

  publish-api:
    runs-on: ubuntu-latest
    needs: build-api
    environment: ${{ github.ref_name == 'main' && 'production' || 'preview' }}
    permissions:
      contents: read
      packages: write
    outputs:
      ImageUrl: ghcr.io/${{ env.REPO }}-api:${{ env.GitVersion_SemVer }}-${{ env.GitVersion_ShortSha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4

      - name: Determine Version
        id: version_step
        run: |
          dotnet tool restore
          dotnet gitversion /output buildserver /updateprojectfiles

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Lowercase the repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v5
        with:
          file: ./Halcyon.Api/Dockerfile
          tags: |
            ghcr.io/${{ env.REPO }}-api:${{ env.GitVersion_SemVer }}
            ghcr.io/${{ env.REPO }}-api:${{ env.GitVersion_SemVer }}-${{ env.GitVersion_ShortSha }}
            ghcr.io/${{ env.REPO }}-api:${{ env.GitVersion_PreReleaseLabel || 'latest' }}
          context: .
          push: true
          provenance: false

  deploy-api:
    runs-on: ubuntu-latest
    needs: 
      - publish-api
    environment: ${{ github.ref_name == 'main' && 'production' || 'preview' }}
    permissions:
      contents: read
    steps:
      - name: Trigger deployment
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            --data "{\"imageUrl\":\"${{ needs.build-and-publish-api.outputs.ImageUrl }}\"}" \
            https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID_API }}/deploys

  build-web:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'production' || 'preview' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: ./Halcyon.Web

      - name: Build and lint
        working-directory: ./Halcyon.Web
        run: |
          npm ci
          npm run lint
          npm run build

  publish-web:
    runs-on: ubuntu-latest
    needs: build-web
    environment: ${{ github.ref_name == 'main' && 'production' || 'preview' }}
    permissions:
      contents: read
      packages: write
    outputs:
      ImageUrl: ghcr.io/${{ env.REPO }}-web:${{ env.GitVersion_SemVer }}-${{ env.GitVersion_ShortSha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4

      - name: Determine Version
        id: version_step
        run: |
          dotnet tool restore
          dotnet gitversion /output buildserver /updateprojectfiles

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: ./Halcyon.Web

      - name: Set version
        working-directory: ./Halcyon.Web
        run: |
          npm version "${{ env.GitVersion_SemVer }}-${{ env.GitVersion_ShortSha }}" --no-git-tag-version

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Lowercase the repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v5
        with:
          file: ./Halcyon.Web/Dockerfile
          tags: |
            ghcr.io/${{ env.REPO }}-web:${{ env.GitVersion_SemVer }}
            ghcr.io/${{ env.REPO }}-web:${{ env.GitVersion_SemVer }}-${{ env.GitVersion_ShortSha }}
            ghcr.io/${{ env.REPO }}-web:${{ env.GitVersion_PreReleaseLabel || 'latest' }}
          context: ./Halcyon.Web
          push: true
          provenance: false

  deploy-web:
    runs-on: ubuntu-latest
    needs: 
      - publish-web
    environment: ${{ github.ref_name == 'main' && 'production' || 'preview' }}
    permissions:
      contents: read
    steps:
      - name: Trigger deployment
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            --data "{\"imageUrl\":\"${{ needs.build-and-publish-web.outputs.ImageUrl }}\"}" \
            https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID_WEB }}/deploys
