name: CI Build and Publish

on:
  push:
    branches: ["main", "develop", "feature/**", "release/**", "hotfix/**"]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'production' || 'preview' }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4

      - name: Determine Version
        id: version_step
        run: |
          dotnet tool restore
          dotnet gitversion /output buildserver /updateprojectfiles

      - name: Build and test (dotnet)
        run: |
          dotnet build "halcyon.sln"
          dotnet test "halcyon.sln"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: ./Halcyon.Web

      - name: Build and lint (npm)
        working-directory: ./Halcyon.Web
        run: |
          npm version "${{ env.GitVersion_SemVer }}-${{ env.GitVersion_ShortSha }}" --no-git-tag-version
          npm ci
          npm run lint
          npm run build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Build and push container image to registry (api)
        uses: docker/build-push-action@v5
        with:
          file: ./Halcyon.Api/Dockerfile
          tags: |
            ghcr.io/${{ env.REPO }}-api:${{ env.GitVersion_SemVer }}
            ghcr.io/${{ env.REPO }}-api:${{ env.GitVersion_SemVer }}-${{ env.GitVersion_ShortSha }}
            ghcr.io/${{ env.REPO }}-api:${{ env.GitVersion_PreReleaseLabel || 'latest' }}
          context: .
          push: true
          provenance: false

      - name: Build and push container image to registry (web)
        uses: docker/build-push-action@v5
        with:
          file: ./Halcyon.Web/Dockerfile
          tags: |
            ghcr.io/${{ env.REPO }}-web:${{ env.GitVersion_SemVer }}
            ghcr.io/${{ env.REPO }}-web:${{ env.GitVersion_SemVer }}-${{ env.GitVersion_ShortSha }}
            ghcr.io/${{ env.REPO }}-web:${{ env.GitVersion_PreReleaseLabel || 'latest' }}
          context: ./Halcyon.Web
          push: true
          provenance: false

      - name: Trigger deployment (api)
        run: |
          curl "${{ secrets.RENDER_DEPLOY_HOOK_URL_API }}&imgURL=ghcr.io/${{ env.REPO }}-api:${{ env.GitVersion_SemVer }}-${{ env.GitVersion_ShortSha }}"

      - name: Trigger deployment (web)
        run: |
          curl "${{ secrets.RENDER_DEPLOY_HOOK_URL_WEB }}&imgURL=ghcr.io/${{ env.REPO }}-web:${{ env.GitVersion_SemVer }}-${{ env.GitVersion_ShortSha }}"
